# Generated by Django 5.1.1 on 2024-11-17 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_onboarding_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_type', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_breed', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_sex', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_age', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_birthday', models.DateField(blank=True, null=True)),
                ('pet_condition', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_health', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_weight', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
