# Generated by Django 5.1.1 on 2024-11-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scheduledservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledservices',
            name='scheduled_time',
        ),
    ]
