# Generated by Django 5.1.1 on 2024-11-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_scheduledservices_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledservices',
            name='scheduled_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
