# Generated by Django 5.1.1 on 2024-11-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_scheduledservices_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledservices',
            name='duration',
        ),
    ]
