# Generated by Django 5.1.1 on 2024-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_scheduledservices_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, default='client', max_length=10, null=True),
        ),
    ]
