# Generated by Django 5.1.1 on 2024-12-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledservices',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
