# Generated by Django 5.1.1 on 2024-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notifications_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notif_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
