# Generated by Django 5.1.1 on 2024-12-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notifications_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledservices',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
