# Generated by Django 5.1.1 on 2024-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_pets_pet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
